### ISSUE TITLE
How to know if it works ?

### ISSUE THREAD

**Issue by nurhanhasan** [trimentor/odoo-k8s-health-check#1]
How to know if it works ?

**Comment by trimentor** [comment]
Hello @nurhun, sorry for the delay, I didn't notice this question until now.

In my case Odoo is running in an OpenShift environment where I've configured the liveness and readiness probes.

In the OpenShift dashboard it is pretty easy to see if everything works as expected (does the POD restart unexpectedly yes/no -> it should behave correctly/expected, so no weird restarts etc.); More information about both probes can be found in the OpenShift docs at https://docs.openshift.com/.

When the module is installed an extra endpoint should be available in your Odoo app: GET /k8s_health_check/status
When your app doesn't respond to this path it means something is not working correctly (for example the module isn't installed/doesn't work/something else).
In case it is installed successfully and when hitting that endpoint you should have a successful response + your logs shouldn't be polluted on each hit.

I hope that answers your question?
